return {
  'ellisonleao/gruvbox.nvim', -- theme
  priority = 99999,
  config = function()
    local bgColor = '#111421'
    require('gruvbox').setup {
      contrast = 'hard',
      transparent_mode = false,
      dim_inactive = false,
      palette_overrides = { dark0_hard = bgColor },
      overrides = {
        NormalFloat = { fg = '#ebdbb2', bg = '#504945' },
        Comment = { fg = '#81878f', italic = true, bold = true },
        Define = { link = 'GruvboxPurple' },
        Macro = { link = 'GruvboxPurple' },
        ['@constant.builtin'] = { link = 'GruvboxPurple' },
        ['@storageclass.lifetime'] = { link = 'GruvboxAqua' },
        ['@text.note'] = { link = 'TODO' },
        ['@namespace.rust'] = { link = 'Include' },
        ['@punctuation.bracket'] = { link = 'GruvboxOrange' },
        texMathDelimZoneLI = { link = 'GruvboxOrange' },
        texMathDelimZoneLD = { link = 'GruvboxOrange' },
        luaParenError = { link = 'luaParen' },
        luaError = { link = 'NONE' },
        ContextVt = { fg = '#878788' },
        CopilotSuggestion = { fg = '#878787' },
        CocCodeLens = { fg = '#878787' },
        CocWarningFloat = { fg = '#dfaf87' },
        CocInlayHint = { fg = '#ABB0B6' },
        CocPumShortcut = { fg = '#fe8019' },
        CocPumDetail = { fg = '#fe8019' },
        DiagnosticVirtualTextWarn = { fg = '#dfaf87' },
        -- fold
        Folded = { fg = '#fe8019', bg = bgColor, italic = true },
        SignColumn = { bg = bgColor },
        -- new git colors
        DiffAdd = {
          bold = true,
          reverse = false,
          fg = '',
          bg = '#2a4333',
        },
        DiffChange = {
          bold = true,
          reverse = false,
          fg = '',
          bg = '#333841',
        },
        DiffDelete = {
          bold = true,
          reverse = false,
          fg = '#442d30',
          bg = '#442d30',
        },
        DiffText = {
          bold = true,
          reverse = false,
          fg = '',
          bg = '#213352',
        },
        -- statusline
        StatusLine = { bg = '#ffffff', fg = bgColor },
        StatusLineNC = { bg = '#3c3836', fg = bgColor },
        CursorLine = { fg = '', bg = '#181C2A' },
        CursorLineNr = { fg = '#fabd2f', bg = '#181C2A' },
        TabLine = { bg = bgColor, fg = bgColor },
        WinSeparator = { bg = bgColor, fg = bgColor },
        TabLineSel = { bg = bgColor, fg = bgColor },
        TabLineFill = { bg = bgColor, fg = bgColor },
        Sep = { bg = bgColor, fg = bgColor },
        BufferTabpageFill = { bg = bgColor, fg = bgColor },
        BufferOffset = { bg = bgColor, fg = bgColor },
        BufferTabpages = { bg = bgColor, fg = bgColor },
        BufferCurrent = { bg = bgColor, fg = '#FABD2F' },
        BufferVisible = { bg = bgColor, fg = '#FABD2F' },
        BufferSep = { bg = bgColor, fg = '#FABD2F' },
        BufferAlternative = { bg = bgColor, fg = '' },
        BufferCurrentSign = { bg = bgColor, fg = '#FABD2F' },
        BufferVisibleSign = { bg = bgColor, fg = '#FABD2F' },
        BufferAlternativeSign = { bg = bgColor, fg = '#FABD2F' },
        BufferCurrentSignRight = { bg = bgColor, fg = '#FABD2F' },
        BufferTabpagesSep = { bg = bgColor, fg = '' },
        BufferInactive = { bg = bgColor, fg = '#AC7F16' },
        BufferInactiveSign = { bg = bgColor, fg = bgColor },
        BufferCurrentIndex = { bg = bgColor, fg = '#FABD2F' },
        BufferCurrentMod = { bg = bgColor, fg = '#FABD2F' },
        BufferCurrentTarget = { bg = bgColor, fg = '#FABD2F' },
        GruvboxOrangeSign = { fg = '#dfaf87', bg = '' },
        GruvboxAquaSign = { fg = '#8EC07C', bg = '' },
        GruvboxGreenSign = { fg = '#b8bb26', bg = '' },
        GruvboxRedSign = { fg = '#fb4934', bg = '' },
        GruvboxBlueSign = { fg = '#83a598', bg = '' },
        WilderMenu = { fg = '#ebdbb2', bg = '' },
        WilderAccent = { fg = '#f4468f', bg = '' },
        -- coc semantic token
        CocSemStruct = { link = 'GruvboxYellow' },
        CocSemKeyword = { fg = '', bg = bgColor },
        CocSemEnumMember = { fg = '', bg = bgColor },
        CocSemTypeParameter = { fg = '', bg = bgColor },
        CocSemComment = { fg = '', bg = bgColor },
        CocSemMacro = { fg = '', bg = bgColor },
        CocSemVariable = { fg = '', bg = bgColor },
        CocSemFunction = { fg = '', bg = bgColor },
        -- neorg
        ['@neorg.markup.inline_macro'] = { link = 'GruvboxGreen' },
      },
    }
    -- vim.cmd 'hi BufferDefaultCurrent guibg=#ffffff guifg=#ffffff'
  end,
}
